# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LetGIb9-s732HwjKHMRjx95N8henqqC5
"""

# app.py  ── minimal Shiny dashboard for the Pokémon optimiser
from shiny import App, reactive, render, ui
import pandas as pd
from optimizer import optimise_team, load_data   # ← uses your CSV

df = load_data()          # one-time load (cached in optimizer.py)

app_ui = ui.page_fluid(
    ui.h2("Pokémon Team Optimiser"),
    ui.layout_sidebar(
        ui.sidebar(
            ui.input_selectize(
                "starter",
                "Choose up to 3 starter Pokémon",
                choices=sorted(df["name"]),
                multiple=True,
                max_items=3,
            ),
            ui.input_slider("hp_floor", "Minimum HP", 1, 255, 60),
            ui.input_action_button("go", "Generate team"),
        ),
        ui.output_data_frame("team_tbl"),
    ),
)

def server(input, output, session):
    @reactive.event(input.go)          # runs only when button is clicked
    def _team():
        return optimise_team(
            starters=input.starter(),
            hp_floor=input.hp_floor(),
        )

    @output
    @render.data_frame
    def team_tbl():
        return _team()                 # DataFrame appears in UI

app = App(app_ui, server)